version: '3.3'

services:
  db:
    container_name: ${DB_CONTAINER}
    image: mariadb:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  wordpress:
    container_name: ${WP_CONTAINER}
    build: wordpress
    depends_on:
      - db
      - composer
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./theme:/var/www/html/wp-content/themes/${THEME_NAME}:rw
      - ./plugin:/var/www/html/wp-content/plugins/${PLUGIN_NAME}:rw
      - wp_content:/var/www/html/wp-content:rw
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}

  composer:
    build: composer
    container_name: ${COMPOSER_CONTAINER}
    volumes:
      - wp_content:/app/wp-content
    command: composer install
volumes:
    db_data:
    wp_content:
